### ISSUE TITLE
Some files could not find

### ISSUE THREAD

**Issue by TrumanZYX** [2cjenn/PRS_Pipeline#8]
Hi, Thanks for your works. 
  I am happy to see the pipeline. But i have to figure out one thing that some files may not get from UKB. I can access the ukb. But i can not find the file (ukb_mfi_chr${i}_v3.txt). We may not get the files again. 
  Or can you provide the way to get the files? Thanks.

**Comment by 2cjenn** [comment]
These files are available from the UK Biobank through the Data Showcase.
The 'ukb_mfi_chr${i}_v3.txt' files can be found, with the other genetic data, in [Category 263](https://biobank.ndph.ox.ac.uk/showcase/label.cgi?id=263).
These files are the 'Imputation MAF + info files', and the 'How to obtain' column links to [Resource 1967](https://biobank.ndph.ox.ac.uk/showcase/refer.cgi?id=1967) which has a direct download link and instructions for downloading a compressed archive of the files using `wget`.

Hope that helps!
